CREATE TABLE [dbo].[OPS_MisRoadSurveyDetails] (
    [RSDetailsId]              INT             IDENTITY (1, 1) NOT NULL,
    [FK_RouteSurveyId]         INT             NOT NULL,
    [RoadConditions]           VARCHAR (1000)  NULL,
    [PowerLineCrossing]        NCHAR (50)      NULL,
    [MaxHeightOfPowerLine]     INT             NULL,
    [MinHeightOfPowerLine]     INT             NULL,
    [WeighingStations]         VARCHAR (50)    NULL,
    [SignBoard]                VARCHAR (50)    NULL,
    [OverBridge]               VARCHAR (50)    NULL,
    [LoadHeightMax]            INT             NULL,
    [LoadWidthMax]             INT             NULL,
    [CrossUnderBridge]         VARCHAR (50)    NULL,
    [UnderBridgeHeight]        INT             NULL,
    [PoliceCheckpoint]         NVARCHAR (50)   NULL,
    [ARAMCOGatePass]           NVARCHAR (50)   NULL,
    [SharpCurvesInRoute]       NVARCHAR (1000) NULL,
    [TITANRequired]            NVARCHAR (50)   NULL,
    [DollyRequired]            NVARCHAR (50)   NULL,
    [HBeamRequired]            NVARCHAR (50)   NULL,
    [RoadRepairRequired]       NVARCHAR (50)   NULL,
    [RoadPermitRequired]       NVARCHAR (50)   NULL,
    [TurrayaRequired]          NVARCHAR (50)   NULL,
    [AdditionalTrucksRequired] NVARCHAR (50)   NULL,
    [AdditionalEqRequired]     NVARCHAR (50)   NULL,
    [PreMoveDate]              DATE            NULL,
    [GasolineProvided]         NVARCHAR (50)   NULL,
    [DieselProvided]           NVARCHAR (50)   NULL,
    [FoodProvided]             NVARCHAR (100)  NULL,
    [RailwayCrossing]          NVARCHAR (100)  NULL,
    [HighwayCrossing]          NVARCHAR (100)  NULL,
    [AramcoSecuirty]           NVARCHAR (100)  NULL,
    [ConvoyRequired]           NVARCHAR (100)  NULL,
    [SolarPanels]              NVARCHAR (100)  NULL,
    [DistanceBtwPanels]        NVARCHAR (100)  NULL,
    [Comments]                 NVARCHAR (MAX)  NULL,
    [CreatedDate]              DATE            NULL,
    CONSTRAINT [PK_OPS_MisRoadSurveyDetails] PRIMARY KEY CLUSTERED ([RSDetailsId] ASC)
);

